export const REQ_SAVE_ACCOUNT_INFO   = "REQ_SAVE_ACCOUNT_INFO";
export const RESP_SAVE_ACCOUNT_INFO  = "RESP_SAVE_ACCOUNT_INFO";
export const ERROR_SAVE_ACCOUNT_INFO = "ERROR_SAVE_ACCOUNT_INFO";

export const REQ_FETCH_ACCOUNT_INFO         = "REQ_FETCH_ACCOUNT_INFO";
export const RESP_FETCH_ACCOUNT_INFO        = "RESP_FETCH_ACCOUNT_INFO";
export const ERROR_FETCH_ACCOUNT_INFO       = "ERROR_FETCH_ACCOUNT_INFO";

export const REQ_REMOVE_ACCOUNT_INFO        = "REQ_REMOVE_ACCOUNT_INFO";
export const ERROR_REMOVE_ACCOUNT_INFO      = "ERROR_REMOVE_ACCOUNT_INFO";
