export const GET_AUTH_USER_PROFILE= 'GET_AUTH_USER_PROFILE';
export const GET_AUTH_USER_PROFILE_SUCCESS = 'GET_AUTH_USER_PROFILE_SUCCESS';
export const GET_AUTH_USER_PROFILE_FAILURE = 'GET_AUTH_USER_PROFILE_FAILURE';