export const GET_ACCOUNTS_BREADCRUMB    = 'GET_ACCOUNTS_BREADCRUMB';
export const GET_BUDGET_BREADCRUMB      = 'GET_BUDGET_BREADCRUMB';
export const GET_BREADCRUMB_SUCCESS     = 'GET_BREADCRUMB_SUCCESS';
export const GET_BREADCRUMB_FAILURE     = 'GET_BREADCRUMB_FAILURE';