export const REQ_CODEVALUES_BYCODEIds   = "REQ_CODEVALUES_BYCODEIds";
export const RESP_CODEVALUES_BYCODEIds  = "RESP_CODEVALUES_BYCODEIds";
export const ERROR_CODEVALUES_BYCODEIds = "ERROR_CODEVALUES_BYCODEIds";